from backend.database import SessionLocal, engine, Base
from backend.models.beach import Beach

Base.metadata.create_all(bind=engine)

beaches = [
    {
        "name": "West Wittering",
        "latitude": 50.7689,
        "longitude": -0.9009,
        "wind_directions": ["SW", "W", "NW"],
        "wind_speed_min": 12,
        "wind_speed_max": 35,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["beginner", "intermediate"],
        "hazards": "Groynes on east side, swimmers near shore at low tide",
        "notes": "Flat water lagoon at high tide, choppy at low. Car park gets busy at weekends.",
        "whatsapp_groups": [],
    },
    {
        "name": "Hayling Island",
        "latitude": 50.7800,
        "longitude": -0.9600,
        "wind_directions": ["SW", "S", "SE"],
        "wind_speed_min": 15,
        "wind_speed_max": 40,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack", "outgoing"],
        "rider_levels": ["intermediate", "advanced"],
        "hazards": "Shallow water at low tide, ferry crossing to east",
        "notes": "Good wave riding in strong SW. Exposed beach, can get gusty.",
        "whatsapp_groups": [],
    },
    {
        "name": "Calshot",
        "latitude": 50.8140,
        "longitude": -1.3040,
        "wind_directions": ["SW", "W", "S"],
        "wind_speed_min": 12,
        "wind_speed_max": 30,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["beginner", "intermediate"],
        "hazards": "Shipping lanes nearby, restricted zones around Calshot Spit",
        "notes": "Sheltered from north. Tidal flow can be strong. Good flat water spot.",
        "whatsapp_groups": [],
    },
    {
        "name": "Lepe",
        "latitude": 50.7830,
        "longitude": -1.3500,
        "wind_directions": ["S", "SW", "SE"],
        "wind_speed_min": 15,
        "wind_speed_max": 35,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["intermediate", "advanced"],
        "hazards": "Strong tidal currents, rocky areas at low tide",
        "notes": "Open water with good chop. Watch tides carefully — current runs fast.",
        "whatsapp_groups": [],
    },
    {
        "name": "Mudeford Sandbank",
        "latitude": 50.7220,
        "longitude": -1.7390,
        "wind_directions": ["SW", "S", "W"],
        "wind_speed_min": 12,
        "wind_speed_max": 35,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["beginner", "intermediate"],
        "hazards": "Narrow channel entrance, boat traffic",
        "notes": "Sheltered inside harbour. Flat water on harbour side. Access by foot or ferry.",
        "whatsapp_groups": [],
    },
    {
        "name": "Sandbanks",
        "latitude": 50.6870,
        "longitude": -1.9460,
        "wind_directions": ["SW", "S", "SE"],
        "wind_speed_min": 15,
        "wind_speed_max": 40,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack", "outgoing"],
        "rider_levels": ["intermediate", "advanced"],
        "hazards": "Ferry crossing, busy beach in summer, swimmers",
        "notes": "Popular spot. Poole Harbour entrance nearby. Good in S/SW winds.",
        "whatsapp_groups": [],
    },
    {
        "name": "Kimmeridge Bay",
        "latitude": 50.6060,
        "longitude": -2.1250,
        "wind_directions": ["S", "SW", "SE"],
        "wind_speed_min": 18,
        "wind_speed_max": 45,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["advanced"],
        "hazards": "Reef and rocks, strong swell, restricted area (MOD firing range nearby)",
        "notes": "World-class wave spot in big S swell. Not for beginners. Check MOD range schedules.",
        "whatsapp_groups": [],
    },
    {
        "name": "Chesil Beach",
        "latitude": 50.5980,
        "longitude": -2.4700,
        "wind_directions": ["S", "SW", "SE"],
        "wind_speed_min": 20,
        "wind_speed_max": 50,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["advanced"],
        "hazards": "Steep shingle beach, heavy shore break, strong undertow",
        "notes": "Powerful wave riding. Dangerous for inexperienced riders. Best in big S swell.",
        "whatsapp_groups": [],
    },
    {
        "name": "Portland Harbour",
        "latitude": 50.5700,
        "longitude": -2.4300,
        "wind_directions": ["NW", "W", "SW", "N", "NE"],
        "wind_speed_min": 12,
        "wind_speed_max": 40,
        "tide_states": ["low", "mid", "high"],
        "tide_directions": ["incoming", "slack", "outgoing"],
        "rider_levels": ["beginner", "intermediate", "advanced"],
        "hazards": "Boat traffic in harbour, stay within designated kite zones",
        "notes": "Olympic sailing venue. Flat water inside harbour. Works in most wind directions. Best flat water spot in Dorset.",
        "whatsapp_groups": [],
    },
    {
        "name": "Weymouth Beach",
        "latitude": 50.6100,
        "longitude": -2.4570,
        "wind_directions": ["S", "SW", "SE"],
        "wind_speed_min": 15,
        "wind_speed_max": 35,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["intermediate"],
        "hazards": "Busy beach in summer, swimmers, pier to west",
        "notes": "Sandy beach with good conditions in S winds. Quieter out of season.",
        "whatsapp_groups": [],
    },
    {
        "name": "Lyme Regis",
        "latitude": 50.7220,
        "longitude": -2.9360,
        "wind_directions": ["S", "SW", "W"],
        "wind_speed_min": 18,
        "wind_speed_max": 40,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["advanced"],
        "hazards": "The Cobb harbour wall, rocks, limited launch area",
        "notes": "Limited space. Better for experienced riders. Good in SW swell.",
        "whatsapp_groups": [],
    },
    {
        "name": "Exmouth",
        "latitude": 50.6190,
        "longitude": -3.4140,
        "wind_directions": ["SW", "S", "W", "NW"],
        "wind_speed_min": 12,
        "wind_speed_max": 35,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["beginner", "intermediate", "advanced"],
        "hazards": "Jet ski zone, sandbanks at low tide, Exe estuary tidal flow",
        "notes": "One of Devon's best kite spots. Flat water in estuary, waves on outside. Kite school on beach.",
        "whatsapp_groups": [],
    },
    {
        "name": "Dawlish Warren",
        "latitude": 50.5980,
        "longitude": -3.4400,
        "wind_directions": ["SW", "W", "NW", "S"],
        "wind_speed_min": 15,
        "wind_speed_max": 40,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["intermediate", "advanced"],
        "hazards": "Nature reserve — no kiting in protected areas, sandbanks",
        "notes": "Good wave spot in SW. Check nature reserve boundaries before launching.",
        "whatsapp_groups": [],
    },
    {
        "name": "Bantham",
        "latitude": 50.2790,
        "longitude": -3.8790,
        "wind_directions": ["SW", "W", "NW"],
        "wind_speed_min": 18,
        "wind_speed_max": 45,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["advanced"],
        "hazards": "River Avon mouth, strong tidal rip, rocks to south",
        "notes": "Stunning location. Powerful waves in SW swell. Strong tidal currents — experienced riders only.",
        "whatsapp_groups": [],
    },
]

db = SessionLocal()

# Skip beaches that already exist
existing = {b.name for b in db.query(Beach.name).all()}
added = 0
for data in beaches:
    if data["name"] not in existing:
        db.add(Beach(**data))
        added += 1

db.commit()
db.close()
print(f"Done — {added} beaches added ({len(existing)} already existed).")
