from backend.database import SessionLocal, engine, Base
from backend.models.beach import Beach

Base.metadata.create_all(bind=engine)

beaches = [
    {
        "name": "West Wittering",
        "latitude": 50.7689,
        "longitude": -0.9009,
        "wind_directions": ["E", "SW", "W", "NW"],
        "wind_speed_min": 12,
        "wind_speed_max": 35,
        "tide_states": ["low", "mid", "high"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["beginner", "intermediate", "advanced"],
        "hazards": "Timber groynes on east side — stay upwind on approach. Easterly wind on outgoing tide creates strong current toward groynes. Very busy in summer.",
        "notes": "All tides work but differently: low tide exposes flat sandbar lagoon (beginners/freestyle), mid is all-round, high produces waves (advanced). SW is classic sideonshore. E (port tack) is excellent on incoming tide. NW is cross-offshore — experienced only. Pre-book car park.",
        "whatsapp_groups": [],
    },
    {
        "name": "Hayling Island",
        "latitude": 50.7800,
        "longitude": -0.9600,
        "wind_directions": ["E", "SE", "S", "SW"],
        "wind_speed_min": 15,
        "wind_speed_max": 40,
        "tide_states": ["low", "mid"],
        "tide_directions": ["incoming", "slack", "outgoing"],
        "rider_levels": ["beginner", "intermediate", "advanced"],
        "hazards": "Concrete blocks, groynes and submerged rocks to the east. Portsmouth-Hayling ferry crossing to east. High tide shrinks beach significantly — leave 3hr gap either side of HW.",
        "notes": "East Winner sandbar appears ~4hrs either side of low tide creating 1km+ flat shallow lagoon — excellent for beginners. Wide wind arc E-SW. CBK is sole school, can run in most directions. Best Apr–Oct.",
        "whatsapp_groups": [],
    },
    {
        "name": "Calshot",
        "latitude": 50.8140,
        "longitude": -1.3040,
        "wind_directions": ["NE", "SE", "S", "SW"],
        "wind_speed_min": 12,
        "wind_speed_max": 30,
        "tide_states": ["low", "mid"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["beginner", "intermediate"],
        "hazards": "Active shipping lane through Southampton Water — never kite in the channel. Strong tidal flow around spit tip, especially on ebb. NW and W winds are offshore/unsafe here.",
        "notes": "Shingle spit at mouth of Southampton Water. Sheltered flat water on inside (Southampton Water side), choppier outside (Solent). One of the only Solent spots that works in NE/N. SW funnelled by IoW can be very strong in afternoon. NW and W do not work. Calshot Activities Centre membership/day pass required.",
        "whatsapp_groups": [],
    },
    {
        "name": "Lepe",
        "latitude": 50.7830,
        "longitude": -1.3500,
        "wind_directions": ["S", "SW", "SE"],
        "wind_speed_min": 15,
        "wind_speed_max": 35,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["intermediate", "advanced"],
        "hazards": "Strong tidal currents, rocky areas at low tide",
        "notes": "Open water with good chop. Watch tides carefully - current runs fast.",
        "whatsapp_groups": [],
    },
    {
        "name": "Mudeford Sandbank",
        "latitude": 50.7220,
        "longitude": -1.7390,
        "wind_directions": ["SW", "S", "W"],
        "wind_speed_min": 12,
        "wind_speed_max": 35,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["beginner", "intermediate"],
        "hazards": "Narrow channel entrance, boat traffic",
        "notes": "Sheltered inside harbour. Flat water on harbour side. Access by foot or ferry.",
        "whatsapp_groups": [],
    },
    {
        "name": "Sandbanks",
        "latitude": 50.6870,
        "longitude": -1.9460,
        "wind_directions": ["SW", "S", "SE"],
        "wind_speed_min": 15,
        "wind_speed_max": 40,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack", "outgoing"],
        "rider_levels": ["intermediate", "advanced"],
        "hazards": "Ferry crossing, busy beach in summer, swimmers",
        "notes": "Popular spot. Poole Harbour entrance nearby. Good in S/SW winds.",
        "whatsapp_groups": [],
    },
    {
        "name": "Kimmeridge Bay",
        "latitude": 50.6060,
        "longitude": -2.1250,
        "wind_directions": ["S", "SW", "SE"],
        "wind_speed_min": 18,
        "wind_speed_max": 45,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["advanced"],
        "hazards": "Reef and rocks, strong swell, restricted area (MOD firing range nearby)",
        "notes": "World-class wave spot in big S swell. Not for beginners. Check MOD range schedules.",
        "whatsapp_groups": [],
    },
    {
        "name": "Chesil Beach",
        "latitude": 50.5980,
        "longitude": -2.4700,
        "wind_directions": ["S", "SW", "SE"],
        "wind_speed_min": 20,
        "wind_speed_max": 50,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["advanced"],
        "hazards": "Steep shingle beach, heavy shore break, strong undertow",
        "notes": "Powerful wave riding. Dangerous for inexperienced riders. Best in big S swell.",
        "whatsapp_groups": [],
    },
    {
        "name": "Portland Harbour",
        "latitude": 50.5700,
        "longitude": -2.4300,
        "wind_directions": ["NW", "W", "SW", "N", "NE"],
        "wind_speed_min": 12,
        "wind_speed_max": 40,
        "tide_states": ["low", "mid", "high"],
        "tide_directions": ["incoming", "slack", "outgoing"],
        "rider_levels": ["beginner", "intermediate", "advanced"],
        "hazards": "Boat traffic in harbour, stay within designated kite zones",
        "notes": "Olympic sailing venue. Flat water inside harbour. Works in most wind directions. Best flat water spot in Dorset.",
        "whatsapp_groups": [{"name": "Portland Harbour Kiters", "invite_link": "https://chat.whatsapp.com/KKUAkjNw5zYKkmPmkpTcE4"}],
    },
    {
        "name": "Weymouth Beach",
        "latitude": 50.6100,
        "longitude": -2.4570,
        "wind_directions": ["S", "SW", "SE"],
        "wind_speed_min": 15,
        "wind_speed_max": 35,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["intermediate"],
        "hazards": "Busy beach in summer, swimmers, pier to west",
        "notes": "Sandy beach with good conditions in S winds. Quieter out of season.",
        "whatsapp_groups": [],
    },
    {
        "name": "Lyme Regis",
        "latitude": 50.7220,
        "longitude": -2.9360,
        "wind_directions": ["S", "SW", "W"],
        "wind_speed_min": 18,
        "wind_speed_max": 40,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["advanced"],
        "hazards": "The Cobb harbour wall, rocks, limited launch area",
        "notes": "Limited space. Better for experienced riders. Good in SW swell.",
        "whatsapp_groups": [],
    },
    {
        "name": "Exmouth",
        "latitude": 50.6190,
        "longitude": -3.4140,
        "wind_directions": ["ESE", "SE", "SSE", "S", "SSW", "SW"],
        "wind_speed_min": 12,
        "wind_speed_max": 35,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["beginner", "intermediate", "advanced"],
        "hazards": "Jet ski zone, sandbanks at low tide, Exe estuary tidal flow",
        "notes": "One of Devon's best kite spots. Flat water in estuary, waves on outside. Kite school on beach.",
        "whatsapp_groups": [],
    },
    {
        "name": "Dawlish Warren",
        "latitude": 50.5980,
        "longitude": -3.4400,
        "wind_directions": ["W", "NW", "N"],
        "wind_speed_min": 15,
        "wind_speed_max": 40,
        "tide_states": ["mid", "high"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["intermediate", "advanced"],
        "hazards": "National Nature Reserve SSSI — kite only in designated zone, no launching over dune vegetation · Sandbanks dry at low tide · Strong tidal current in Exe channel · Ferries cross estuary mouth",
        "notes": "NW funnelled by Exe estuary gives clean side-shore conditions. W and N also work. Best 2hrs either side of high tide. Quieter and less crowded than Exmouth beach.",
        "whatsapp_groups": [],
    },
    {
        "name": "Duckpond (Exmouth)",
        "latitude": 50.62274,
        "longitude": -3.41796,
        "wind_directions": ["N", "NW", "NNW"],
        "wind_speed_min": 12,
        "wind_speed_max": 35,
        "tide_states": ["high", "mid"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["beginner", "intermediate", "advanced"],
        "hazards": "Shallow lagoon. Empties quick on spring tides.",
        "notes": "Flat water from 2hrs before to 2hrs after high tide. Drains quickly at springs.",
        "whatsapp_groups": [],
    },
    {
        "name": "Bantham",
        "latitude": 50.2790,
        "longitude": -3.8790,
        "wind_directions": ["SW", "W", "NW"],
        "wind_speed_min": 18,
        "wind_speed_max": 45,
        "tide_states": ["low", "mid"],
        "tide_directions": ["incoming", "slack"],
        "rider_levels": ["advanced"],
        "hazards": "River Avon mouth rip — strong tidal current on ebb · High tide shrinks beach, avoid last 2hrs of flood · Rocks to south of bay · No lifeguard cover",
        "notes": "Expert wave spot. Low to mid tide essential — at high water the beach narrows and river mouth becomes turbulent. SW 20-30kt with 2-3ft swell produces excellent right-handers. Check tide tables carefully.",
        "whatsapp_groups": [],
    },
]

db = SessionLocal()

existing = {b.name for b in db.query(Beach.name).all()}
added = 0
for data in beaches:
    if data["name"] not in existing:
        try:
            db.add(Beach(**data))
            db.commit()
            added += 1
            print(f"Added: {data['name']}")
        except Exception as e:
            db.rollback()
            print(f"Failed to add {data['name']}: {e}")

db.close()
print(f"Done - {added} beaches added ({len(existing)} already existed).")
